### ISSUE TITLE
MQTT authentication not working

### ISSUE THREAD

**Issue by jonoxer** [OXRS-IO/OXRS-IO-MQTT-ESP32-LIB#5]
Authentication fails when setting MQTT_USERNAME and MQTT_PASSWORD in config, which is then passed to:

mqtt.setAuth(MQTT_USERNAME, MQTT_PASSWORD);

Editing the library to set the username and password directly in src/OXRS_MQTT.cpp on line 172 works fine, so it's something to do with passing in the values.

I plan to fix this myself: just putting it here as an issue to remind myself later.

**Comment by sumnerboy12** [comment]
I have finally got this code running locally and am seeing the same thing - it is a problem with the way I am trying to use `#ifdef` with const char variables.

**Comment by sumnerboy12** [comment]
See https://github.com/SuperHouse/OXRS-SHA-StateMonitor-ESP32-FW/pull/9
