### ISSUE TITLE
move screen.show_event() into MQTT lib

### ISSUE THREAD

**Issue by moinmoin-sh** [OXRS-IO/OXRS-IO-MQTT-ESP32-LIB#7]
check if `screen.show_event` can be moved into `boolean OXRS_MQTT::publishStatus(JsonObject json)`
This would elimnate a further `screen `call from the FW

**Comment by sumnerboy12** [comment]
Not sure you can know what the event will be or look like. I think the
event display on screen needs to be controlled by the firmware.

Who knows what someone will want to display...

**Comment by moinmoin-sh** [comment]
OK, agree

but looked very promissing for our use case
